- action:
  - service: script.1523505263098
  alias: Playroom Fan Level 1
  condition: []
  id: '1523506259174'
  trigger:
  - entity_id: input_select.playroom_fan
    platform: state
    to: Level 1
